version: '3.1'

services:
  todo_app:
    build: .
    container_name: todo_app
    depends_on:
      - mysql_db
    restart: always
    ports:
     - "80:8686"
    environment:
      MYSQL_HOST: mysql_db

  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./dbdata:/var/lib/mysql/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080